VERSION 0.7

deps:
    FROM golang:1.18-alpine
    WORKDIR /common-libs
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY commons ./commons
    COPY utilities ./utilities
    SAVE ARTIFACT .

unit-test:
    FROM +artifact
    RUN CGO_ENABLED=0 go test github.com/gigiozzz/depiy/common-libs/utilities