# permissions for end users to view entandopluginv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandopluginv2-viewer-role
rules:
- apiGroups:
  - plugin.entando.org
  resources:
  - entandopluginv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plugin.entando.org
  resources:
  - entandopluginv2s/status
  verbs:
  - get
