VERSION 0.7

deps:
    FROM golang:1.18-alpine
    WORKDIR /build/operators/bundle-operator
    COPY ../../common-libs+artifact/* /build/common-libs
    COPY ../gateway-operator+compile/* /build/operators/gateway-operator
    COPY ../plugin-operator+compile/* /build/operators/plugin-operator
    COPY go.mod go.sum ./
    RUN go mod download

compile:
    FROM +deps
    COPY main.go main.go
    COPY api ./api
    COPY bundles/ bundles/
    COPY controllers ./controllers
    RUN cd /build \
        && go work init \
        && go work use ./common-libs \
        && go work use ./operators/gateway-operator \
        && go work use ./operators/plugin-operator \
        && go work use ./operators/bundle-operator
    RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o bundle-manager main.go
    SAVE ARTIFACT .

unit-test:
    FROM +compile
    RUN CGO_ENABLED=0 go test