# permissions for end users to edit entandobundlev2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandobundlev2-editor-role
rules:
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundlev2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundlev2s/status
  verbs:
  - get
