# permissions for end users to edit entandobundleinstancev2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandobundleinstancev2-editor-role
rules:
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundleinstancev2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundleinstancev2s/status
  verbs:
  - get
