# permissions for end users to view entandobundlev2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandobundlev2-viewer-role
rules:
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundlev2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bundle.entando.org
  resources:
  - entandobundlev2s/status
  verbs:
  - get
