# permissions for end users to edit entandogatewayv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandogatewayv2-editor-role
rules:
- apiGroups:
  - gateway.entando.org
  resources:
  - entandogatewayv2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.entando.org
  resources:
  - entandogatewayv2s/status
  verbs:
  - get
