# permissions for end users to view entandogatewayv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandogatewayv2-viewer-role
rules:
- apiGroups:
  - gateway.entando.org
  resources:
  - entandogatewayv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.entando.org
  resources:
  - entandogatewayv2s/status
  verbs:
  - get
